'use client';

export default function AIAnalysis({ summary }) {
    if (!summary) return null;

    const content = summary.analysis || summary;

    // Simple markdown-like rendering
    const renderContent = (text) => {
        if (typeof text !== 'string') return <p>{JSON.stringify(text)}</p>;

        return text.split('\n').map((line, i) => {
            // Headers
            if (line.startsWith('## ')) {
                return <h3 key={i} style={{
                    fontSize: '16px', fontWeight: 700, color: 'var(--text-primary)',
                    margin: '16px 0 8px', borderBottom: '1px solid var(--border-color)',
                    paddingBottom: '6px'
                }}>{line.replace('## ', '')}</h3>;
            }
            if (line.startsWith('**') && line.endsWith('**')) {
                return <p key={i} style={{ fontWeight: 600, color: 'var(--text-primary)', margin: '12px 0 4px' }}>
                    {line.replace(/\*\*/g, '')}
                </p>;
            }
            // Bold text in line
            if (line.includes('**')) {
                const parts = line.split('**');
                return (
                    <p key={i} style={{ margin: '4px 0', lineHeight: 1.7 }}>
                        {parts.map((part, j) =>
                            j % 2 === 1 ? <strong key={j} style={{ color: 'var(--text-primary)' }}>{part}</strong> : part
                        )}
                    </p>
                );
            }
            // Bullet points
            if (line.startsWith('• ') || line.startsWith('- ') || line.startsWith('* ')) {
                return <li key={i} style={{ marginLeft: '16px', marginBottom: '4px', lineHeight: 1.7 }}>
                    {line.replace(/^[•\-\*]\s/, '')}
                </li>;
            }
            // Empty lines
            if (line.trim() === '') return <br key={i} />;
            // Normal text
            return <p key={i} style={{ margin: '4px 0', lineHeight: 1.7 }}>{line}</p>;
        });
    };

    return (
        <div className="ai-summary-content">
            {renderContent(content)}
            {summary.model && (
                <div style={{
                    marginTop: '16px',
                    padding: '8px 12px',
                    background: 'rgba(0,0,0,0.2)',
                    borderRadius: '8px',
                    fontSize: '11px',
                    color: 'var(--text-muted)',
                    display: 'flex',
                    justifyContent: 'space-between'
                }}>
                    <span>🤖 Generated by AI</span>
                    <span>{new Date(summary.generatedAt).toLocaleString()}</span>
                </div>
            )}
        </div>
    );
}
